services:
  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kafka-poc
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin12!@
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [CMD, mysqladmin, ping, -h, localhost]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - kafka-net

