services:
  redis:
    image: redis:7
    container_name: local-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: [CMD, redis-cli, ping]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - kafka-net

